# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdd02cda971e7be755ff6f6b92a115e5b811c861869f714b7ff362a7105e7f5e98cd20540d7e378e045f9d1fff4671c2a5041100f21c13c971b67f11f58c68c8

test:
  secret_key_base: be09eaac99bc700b9ea8f209b1700ad0a4ea7b948a4fe9ebcc93472f72f3be8a960ed9aaf1de506326dd8ca3745ed68d7563c4c042eb4feb97e308793ce3a8d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
